### ISSUE TITLE
Weighting pathways by strength (e.g., citation count)?

### ISSUE THREAD

**Issue by SamuelMarks** [PathwayMerger/PathMe#36]
PathMe looks pretty good. Nice work!

At a glance it seems to focus on established pathways, so will miss more tenuous links.

Related to this would be the opportunity to weight the strength of evidence of links (i.e. is it in 1 paper or 50?).

If I wanted to contribute these features to PathMe, how would I go about doing so?

(also would welcome your opinion on the ideas themselves)

Thanks

**Comment by ddomingof** [comment]
Sorry @SamuelMarks.
Somehow I have not received notifications for my repos and didnt reply. 

> Related to this would be the opportunity to weight the strength of evidence of links (i.e. is it in 1 paper or 50?).
This is unfortunately not possible since this information is not available. I would use LLMs or databases like STRING to weight the proteins.

> If I wanted to contribute these features to PathMe, how would I go about doing so?
Happy to accept PRs, I saw you had one that has now been merged.
